Document: ddgrey
Title: Debian ddgrey Manual
Author: <insert document author here>
Abstract: This manual describes what ddgrey is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ddgrey/ddgrey.sgml.gz

Format: postscript
Files: /usr/share/doc/ddgrey/ddgrey.ps.gz

Format: text
Files: /usr/share/doc/ddgrey/ddgrey.text.gz

Format: HTML
Index: /usr/share/doc/ddgrey/html/index.html
Files: /usr/share/doc/ddgrey/html/*.html
